// HW Change List 워크플로우 공통 데이터

// Jira 스타일 상태 컬러 (Atlassian lozenge 팔레트)
export const STATUS_META = {
  'To Do': {
    key: 'todo',
    bg: '#DFE1E6',
    fg: '#42526E',
    color: '#5E6C84',
    description: '설계 담당자가 HW Guide 이슈를 생성하고 Description을 작성하는 단계',
    entryCriteria: '이슈 생성 직후',
    exitCriteria: 'Description 작성 완료, Assignee를 DV 담당자로 변경',
    owner: 'Design → DV',
  },
  'In Review': {
    key: 'in-review',
    bg: '#DEEBFF',
    fg: '#0052CC',
    color: '#0052CC',
    description: 'DV 담당자가 HW 변경사항을 확인하고 리뷰하는 단계',
    entryCriteria: 'DV 담당자가 Assignee 적절성 확인 후 In Review로 변경',
    exitCriteria: 'HW 변경사항 리뷰 완료, Comment로 문의사항 정리',
    owner: 'DV',
  },
  'In Verification': {
    key: 'in-verification',
    bg: '#DEEBFF',
    fg: '#0747A6',
    color: '#0747A6',
    description: 'DV가 HW 검증을 수행하는 단계',
    entryCriteria: '리뷰 완료 후 In Verification으로 변경',
    exitCriteria: '검증 수행 완료, (2) DV Verification 포맷 작성',
    owner: 'DV',
  },
  'Verified': {
    key: 'verified',
    bg: '#EAE6FF',
    fg: '#5243AA',
    color: '#5243AA',
    description: 'DV 검증이 완료되어 각 부서가 리뷰를 시작하는 단계',
    entryCriteria: '(2) DV Verification 작성 완료',
    exitCriteria: 'DV→Design→Platform/SW 순 리뷰, 각자 Comment 작성',
    owner: 'DV → Design → Platform/SW',
  },
  'Reviewed': {
    key: 'reviewed',
    bg: '#EAE6FF',
    fg: '#403294',
    color: '#403294',
    description: '모든 부서 리뷰 완료, Validation 시작을 준비하는 단계',
    entryCriteria: '모든 Assignee 리뷰 Comment 작성 완료, Review Subtask Done',
    exitCriteria: 'Platform/SW 담당자로 Assignee 변경',
    owner: 'Platform / SW',
  },
  'In Validation': {
    key: 'in-validation',
    bg: '#FFF0B3',
    fg: '#974F0C',
    color: '#974F0C',
    description: 'Platform 또는 SW가 Validation을 수행하는 단계',
    entryCriteria: 'Assignee를 Validation 담당자로 변경',
    exitCriteria: '(3) SW Feature/Validation 작성, Subtask Done, 필요 시 Re-assign',
    owner: 'Platform / SW',
  },
  'Validated': {
    key: 'validated',
    bg: '#E3FCEF',
    fg: '#006644',
    color: '#006644',
    description: 'Platform/SW Validation이 모두 완료된 상태',
    entryCriteria: 'Platform + SW 모두 Validation 기재, Subtask Done',
    exitCriteria: 'Assignee를 설계 담당자로 변경',
    owner: 'Platform/SW → Design',
  },
  'Closed': {
    key: 'closed',
    bg: '#E3FCEF',
    fg: '#064',
    color: '#064',
    description: '설계 담당자가 최종 컨펌을 마치고 종료된 상태',
    entryCriteria: '설계 담당자가 Validation 결과 확인',
    exitCriteria: '(종료) — 필요 시 TL/Design/DV/Platform/SW가 Reopen',
    owner: 'Design',
  },
};

export const ROLES = {
  design: {
    label: '설계 (Design)',
    short: 'Design',
    color: '#0052CC',
    emoji: 'D',
    responsibility: 'HW 변경 사항 작성 및 DV/Platform/SW 검증 내용 확인 후 최종 컨펌',
    stages: ['To Do', 'Verified', 'Validated', 'Closed'],
  },
  dv: {
    label: 'DV (HW 검증)',
    short: 'DV',
    color: '#5243AA',
    emoji: 'V',
    responsibility: 'HW 변경 사항 확인 후 HW 검증 수행',
    stages: ['To Do', 'In Review', 'In Verification', 'Verified'],
  },
  platform: {
    label: 'Platform',
    short: 'Platform',
    color: '#974F0C',
    emoji: 'P',
    responsibility: 'HW 변경 사항 / 검증 내용 리뷰 후 Platform Validation',
    stages: ['Verified', 'Reviewed', 'In Validation', 'Validated'],
  },
  sw: {
    label: 'SW',
    short: 'SW',
    color: '#006644',
    emoji: 'S',
    responsibility: 'HW 변경 사항 / 검증 내용 리뷰 후 SW Validation',
    stages: ['Verified', 'Reviewed', 'In Validation', 'Validated'],
  },
};

export const WORKFLOW_STEPS = [
  {
    id: 'step-1',
    from: 'To Do',
    to: 'To Do',
    actor: 'design',
    title: 'HW Guide 이슈 생성 & Description 작성',
    description:
      '설계 담당자가 Jira에 HW Guide 이슈(SOCSW)를 생성한다. DV/SW/Platform 담당자가 HW 변경사항을 명확히 이해할 수 있도록 지정된 포맷에 따라 Description을 작성한다.',
    action: '작성 완료 후 Assignee를 DV 담당자로 변경',
    checklist: [
      'SOCSW 프로젝트에 HW Guide 이슈 생성',
      '지정된 포맷에 따라 Description 작성',
      'HW 변경 사항을 DV/SW/Platform이 이해할 수 있도록 명확히 기술',
      'Assignee를 DV 담당자로 변경',
    ],
  },
  {
    id: 'step-2',
    from: 'To Do',
    to: 'In Review',
    actor: 'dv',
    title: 'Assignee 확인 & 리뷰 시작',
    description:
      'DV 담당자는 Assignee가 자신에게 지정된 것이 적절한지 확인한 후 Status를 In Review로 변경한다.',
    action: 'Status → In Review',
    checklist: [
      'Assignee 적절성 확인',
      '부적절할 경우 올바른 DV 담당자로 재지정',
      'Status를 In Review로 변경',
    ],
  },
  {
    id: 'step-3',
    from: 'In Review',
    to: 'In Verification',
    actor: 'dv',
    title: 'HW 변경 사항 리뷰',
    description:
      'DV 담당자는 HW 변경사항 정보를 확인하고 리뷰를 시작한다. 리뷰 과정에서 문의사항이 있는 경우 Comment를 통해 설계자에게 문의한다.',
    action: '리뷰 완료 후 Status → In Verification',
    checklist: [
      'HW 변경사항 Description 리뷰',
      '문의사항이 있으면 Comment로 설계자에게 문의',
      '리뷰 완료 후 Status를 In Verification으로 변경',
    ],
  },
  {
    id: 'step-4',
    from: 'In Verification',
    to: 'Verified',
    actor: 'dv',
    title: 'HW 검증 수행',
    description:
      'DV가 검증을 수행한다. 검증이 완료되면 포맷 중 (2) DV Verification을 작성한다.',
    action: '검증 내용 작성 후 Status → Verified',
    checklist: [
      'HW 검증 수행',
      '(2) DV Verification 섹션에 검증 결과 작성',
      'Status를 Verified로 변경',
    ],
  },
  {
    id: 'step-5',
    from: 'Verified',
    to: 'Reviewed',
    actor: 'platform',
    title: '각 부서 교차 리뷰 (DV → Design → Platform/SW)',
    description:
      '각 담당자별로 HW 변경사항과 DV 결과에 대한 리뷰를 진행한다. DV → Design → Platform/SW 순으로 Assignee를 변경하며 리뷰 결과를 Comment에 작성한다. Platform/SW는 별도 Review Subtask를 Done 처리한다.',
    action: '마지막 Assignee가 리뷰 완료 후 Status → Reviewed',
    checklist: [
      'DV → Design → Platform/SW 순으로 Assignee 변경',
      '각 담당자가 Comment로 리뷰 결과 작성',
      'Platform/SW Review Subtask를 Done 처리',
      '마지막 Assignee가 Status를 Reviewed로 변경',
    ],
  },
  {
    id: 'step-6',
    from: 'Reviewed',
    to: 'In Validation',
    actor: 'platform',
    title: 'Validation 시작 준비',
    description:
      'Assignee를 Validation을 시작할 Platform 또는 SW 담당자로 변경한다.',
    action: 'Assignee 변경 후 Status → In Validation',
    checklist: [
      'Assignee를 Platform 또는 SW Validation 담당자로 변경',
      'Status를 In Validation으로 변경',
    ],
  },
  {
    id: 'step-7',
    from: 'In Validation',
    to: 'Validated',
    actor: 'sw',
    title: 'Platform / SW Validation 수행',
    description:
      'Assignee는 Validation을 진행한다. Validation 결과를 (3) SW Feature/Validation에 작성하고 Subtask를 Done 처리한다. 현재 Platform/SW Validation Workflow가 분리되어 있지 않으므로 필요 시 Re-assign하여 Validation을 진행한다. (Pilot 후 Workflow 분리 수립 예정)',
    action: 'Platform + SW 모두 완료 시 Status → Validated',
    checklist: [
      'Platform Validation 수행',
      'SW Validation 수행',
      '(3) SW Feature/Validation에 결과 기재',
      'Validation Subtask Done 처리',
      '필요 시 Re-assign하여 다른 담당자에게 전달',
      'Platform + SW 모두 기재 & Subtask Done이면 Validated로 변경',
    ],
  },
  {
    id: 'step-8',
    from: 'Validated',
    to: 'Closed',
    actor: 'design',
    title: '설계 최종 컨펌 & 종료',
    description:
      '설계 담당자가 Validation 사항에 대해 최종 컨펌할 수 있도록 Assignee를 설계 담당자로 변경한다. 설계 담당자는 Validation 결과를 확인하고 HW 변경사항이 제대로 검증되었는지 확인한다.',
    action: '확인 완료 후 Status → Closed (Reopen 필요 시 TL/Design/DV/Platform/SW 가능)',
    checklist: [
      'Assignee를 설계 담당자로 변경',
      'Validation 결과 확인',
      'HW 변경사항의 검증 완결성 확인',
      'Status를 Closed로 변경',
      '이슈 발견 시 Reopen 가능 (TL/Design/DV/Platform/SW)',
    ],
  },
];

export const STATUS_FLOW = [
  'To Do',
  'In Review',
  'In Verification',
  'Verified',
  'Reviewed',
  'In Validation',
  'Validated',
  'Closed',
];
